# Generated by Django 3.2.5 on 2021-12-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_number',
            field=models.CharField(max_length=13, null=True, verbose_name='Contact Number'),
        ),
    ]
