# Generated by Django 3.2.5 on 2021-12-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0003_auto_20211220_0251'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(default='customer/images/custdefault.jpg', upload_to='customer/images'),
        ),
    ]
