# Generated by Django 3.2.5 on 2022-03-03 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_alter_customer_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='complete_info',
            field=models.BooleanField(default=False, verbose_name='Complete Registraiton'),
        ),
    ]
