# Generated by Django 3.2.5 on 2021-12-24 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0002_product_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='shopowner',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='shopowner.shopowner'),
        ),
        migrations.AlterField(
            model_name='shop',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
