# Generated by Django 3.2.5 on 2021-12-30 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0004_auto_20211224_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='product/images/product_default.jpg', upload_to='product/images'),
        ),
        migrations.AddField(
            model_name='shop',
            name='image',
            field=models.ImageField(default='shop/images/shop_default.jpg', upload_to='shop/images'),
        ),
        migrations.AddField(
            model_name='shopowner',
            name='image',
            field=models.ImageField(default='shopowner/images/shopowner_default.jpg', upload_to='shopowner/images'),
        ),
    ]
