# Generated by Django 3.2.5 on 2022-01-01 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0005_auto_20211230_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Kg', max_length=50),
        ),
    ]
