# Generated by Django 3.2.5 on 2022-01-11 11:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0004_customer_image'),
        ('shopowner', '0006_product_unit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('tag', models.CharField(default='review', max_length=50)),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
                ('product', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopowner.product')),
                ('shop', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='shopowner.shop')),
            ],
        ),
    ]
