# Generated by Django 3.2.5 on 2022-01-13 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopowner', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
    ]
